feat: update mpich to 4.2.0-6

diff --git a/debian/patches/0002-autogen.sh-Avoid-debian-buggy-which-output.patch b/debian/patches/0002-autogen.sh-Avoid-debian-buggy-which-output.patch
--- a/debian/patches/0002-autogen.sh-Avoid-debian-buggy-which-output.patch
+++ b/debian/patches/0002-autogen.sh-Avoid-debian-buggy-which-output.patch
@@ -15,16 +15,14 @@ Signed-off-by: Boyuan Yang <byang@debian.org>
  autogen.sh | 2 +-
  1 file changed, 1 insertion(+), 1 deletion(-)
 
-diff --git a/autogen.sh b/autogen.sh
-index 839b013..00bc84d 100755
 --- a/autogen.sh
 +++ b/autogen.sh
-@@ -545,7 +545,7 @@ fi
- ########################################################################
+@@ -812,7 +812,7 @@
  
- echo_n "Checking for bash... "
--if test "`which bash 2>&1 > /dev/null ; echo $?`" = "0" ;then
-+if test "`command -v bash 2>&1 > /dev/null ; echo $?`" = "0" ;then
-     echo "done"
- else
-     echo "bash not found" ;
+ fn_check_bash_find_patch_xargs() {
+     echo_n "Checking for bash... "
+-    if test "`which bash 2>&1 > /dev/null ; echo $?`" = "0" ;then
++    if test "`command -v bash 2>&1 > /dev/null ; echo $?`" = "0" ;then
+         echo "done"
+     else
+         echo "bash not found" ;
